# Table Creation

create table CovidVaccinations (
	iso_code 	text,
    continent	text,
    location	text,
    date	text,
    new_tests	int,
    total_tests	int,
    total_tests_per_thousand double,
	new_tests_per_thousand	double,
    new_tests_smoothed	int,
    new_tests_smoothed_per_thousand	double,
    positive_rate	double,
    tests_per_case	double,
    tests_units	text,
    total_vaccinations	int,
    people_vaccinated	int,
    people_fully_vaccinated	int,
    new_vaccinations	int,
    new_vaccinations_smoothed	int,
    total_vaccinations_per_hundred	double,
    people_vaccinated_per_hundred	double,
    people_fully_vaccinated_per_hundred	double,
    new_vaccinations_smoothed_per_million	double,
    stringency_index	double,
    population_density	double,
    median_age	double,
    aged_65_older	double,
    aged_70_older	double,
    gdp_per_capita	double,
    extreme_poverty	text,
    cardiovasc_death_rate	double,
    diabetes_prevalence	double,
    female_smokers	double,
    male_smokers	double,
    handwashing_facilities	double,
    hospital_beds_per_thousand	double,
    life_expectancy	double,
    human_development_index	double,
    excess_mortality	double
);

create table CovidDeaths (
	iso_code	text,
    continent	text,
    location	text,
    date	text,
    population	int,
    total_cases	int,	
    new_cases	int,
    new_cases_smoothed	double,	
    total_deaths	int,
    new_deaths	int,
    new_deaths_smoothed		double,
    total_cases_per_million	double,
    new_cases_per_million	double,
    new_cases_smoothed_per_million	double,	
    total_deaths_per_million	double,
    new_deaths_per_million	double,
    new_deaths_smoothed_per_million	double,	
    reproduction_rate	double,
    icu_patients	int,
    icu_patients_per_million	int,	
    hosp_patients	int,
    hosp_patients_per_million	double,
    weekly_icu_admissions	int,
    weekly_icu_admissions_per_million	double,
    weekly_hosp_admissions	int,
    weekly_hosp_admissions_per_million	double
);
